### ISSUE TITLE
Both way of Define and Use Custom Chart Palette aren't working

### ISSUE THREAD

**Issue by KexyBiscuit** [telerik/uwp-docs#70]
I tried Define a Palette in Code-behind and Define a Palette in XAML. The latter caused a runtime error, and the other doesn't work at all.

**Comment by LanceMcCarthy** [comment]
Hi Garfield, this repo is specifically for the documentation for the Universal Windows Platform controls.

If you'd help for a technical problem, you can open a post here  [UI for UWP - Chart](https://www.telerik.com/forums/ui-for-universal-windows-platform/chart) 

Please include:
* The code you used (xaml and c#)
* The version of UI for UWP
* The min and target SDK of the UWP project.

**Comment by Garfield550** [comment]
@LanceMcCarthy Hi Lance, I'm Garfield, Kexy is my friend. :grinning:
