### ISSUE TITLE
How to set focus to textbox in edit mode of Raddatagrid in UWP

### ISSUE THREAD

**Issue by satyaprakashrevu** [telerik/uwp-docs#97]
How to set focus to a textbox in edit mode of Raddatagrid in Tapped event in UWP

**Comment by LanceMcCarthy** [comment]
Hi @satyaprakashrevu this is not an issue with the source code of the UWP documentation, therefore I am marking this as closed. For requesting technical assistance using the components, please visit https://www.telerik.com/account/support-center or https://www.telerik.com/forums. Thanks!
